#!/bin/sh

echo "-----Fixing FontForge debris and normalizing UFOs..."
psffixffglifs source/masters/GentiumPlusMaster-Regular.ufo -p checkfix=fix
wait

echo "-----Updating production names in Regular..."
psfsetpsnames -q -p checkfix=fix -i source/glyph_data.csv source/masters/GentiumPlusMaster-Regular.ufo -p backup=False -x

echo "-----Updating glyph orders in Regular..."
psfsetglyphorder -q --header sort_final_cdg -i source/glyph_data.csv source/masters/GentiumPlusMaster-Regular.ufo -p backup=False -x

echo "-----Rebuilding composites..."
psfbuildcomp -i source/composites.txt -c -n source/masters/GentiumPlusMaster-Regular.ufo -p backup=False

echo "-----Preflight completed!"
