#!/bin/sh

echo "-----Updating UFOs from Glyphs file..."
psfglyphs2ufo --nofea source/masters/GentiumPlusWSP.glyphs source/masters
wait

echo "-----Normalizing Regular UFO..."
echo "-----Updating production names in Regular..."
psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/masters/GentiumPlusMaster-Regular.ufo -x

echo "-----Updating glyph orders in Regular..."
psfsetglyphorder -q --header sort_final_cdg -i source/glyph_data.csv source/masters/GentiumPlusMaster-Regular.ufo -p backup=False -x

echo "-----Rebuilding composites..."
psfbuildcomp -i source/composites.txt -c -n source/masters/GentiumPlusMaster-Regular.ufo -p backup=False

echo "-----Preflight completed!"
